In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
print(pd.__version__)

2.3.3

In [ ]:
# DataFrame

In [5]:
df = pd.DataFrame([10,20,30] , columns = ['col_name'])
print(df)

   col_name
0        10
1        20
2        30

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
# Data Created

data = {
    'Name' : ['Amit','Sumit','Jadu','Rahul'],
    'Age' : [23,22,22,26],
    'Salary' : [90000,30000,45000,55000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Salary
0   Amit   23   90000
1  Sumit   22   30000
2   Jadu   22   45000
3  Rahul   26   55000

In [8]:
df

    Name  Age  Salary
0   Amit   23   90000
1  Sumit   22   30000
2   Jadu   22   45000
3  Rahul   26   55000

In [ ]:
# basic dataframe operation

In [9]:
df.head()

    Name  Age  Salary
0   Amit   23   90000
1  Sumit   22   30000
2   Jadu   22   45000
3  Rahul   26   55000

In [11]:
df.tail(2)

    Name  Age  Salary
2   Jadu   22   45000
3  Rahul   26   55000

In [13]:
# find row and column
df.shape

(4, 3)

In [14]:
# only column
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [16]:
# rename column
df.rename(columns= {'Salary' : 'Monthly_Salary'})

    Name  Age  Monthly_Salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000

In [17]:
df

    Name  Age  Salary
0   Amit   23   90000
1  Sumit   22   30000
2   Jadu   22   45000
3  Rahul   26   55000

In [18]:
# save in variable

df = df.rename(columns= {'Salary' : 'Monthly_salary'})
df

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000

In [19]:
# using inplace to save a changes

df.rename(columns= {'Salary' : 'Monthly_salary'}, inplace = True)
df

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [21]:
df.describe()

             Age  Monthly_salary
count   4.000000        4.000000
mean   23.250000    55000.000000
std     1.892969    25495.097568
min    22.000000    30000.000000
25%    22.000000    41250.000000
50%    22.500000    50000.000000
75%    23.750000    63750.000000
max    26.000000    90000.000000

In [22]:
# save data file with index

df.to_csv('Test_data.csv')

In [23]:
# save data file without index

df.to_csv('Test_data_WithoutIndex.csv', index = False)

In [27]:
# load csv file
df = pd.read_csv('Test_data_WithoutIndex.csv')

In [28]:
df

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000
4   samu   24           50000
5   jamu   23           30000

In [29]:
print(df)

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000
4   samu   24           50000
5   jamu   23           30000

In [30]:
# row and column selection 

# select columns

df[['Name' , 'Age']]

    Name  Age
0   Amit   23
1  Sumit   22
2   Jadu   22
3  Rahul   26
4   samu   24
5   jamu   23

In [31]:
# select row

# index base selection 
df.loc[df.Name=='Amit']

   Name  Age  Monthly_salary
0  Amit   23           90000

In [32]:
df.loc[df.Name=='samu']

   Name  Age  Monthly_salary
4  samu   24           50000

In [33]:
# condition to print 
df.loc[(df.Name=='Amit') & (df.Age>=19)]

   Name  Age  Monthly_salary
0  Amit   23           90000

In [34]:
# iloc index based value
df.iloc[0]

Name               Amit
Age                  23
Monthly_salary    90000
Name: 0, dtype: object

In [35]:
df.iloc[0:2]

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000

In [36]:
df.loc[0:2]

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000

In [37]:
print(df)

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000
4   samu   24           50000
5   jamu   23           30000

In [38]:
df

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000
4   samu   24           50000
5   jamu   23           30000

In [39]:
# true false
# only return true or false

df['Age'] > 22

0     True
1    False
2    False
3     True
4     True
5     True
Name: Age, dtype: bool

In [40]:
# value
df[df['Age'] > 22]

    Name  Age  Monthly_salary
0   Amit   23           90000
3  Rahul   26           55000
4   samu   24           50000
5   jamu   23           30000

In [41]:
# multiple condition 

df[(df['Age'] >= 19 ) & (df['Monthly_salary'] >= 80000)]

   Name  Age  Monthly_salary
0  Amit   23           90000

In [43]:
# non value print
df.where(df['Age'] >= 23)

    Name   Age  Monthly_salary
0   Amit  23.0         90000.0
1    NaN   NaN             NaN
2    NaN   NaN             NaN
3  Rahul  26.0         55000.0
4   samu  24.0         50000.0
5   jamu  23.0         30000.0

In [44]:
df.where(df['Age'] >= 23 , other = 'not eligible')

           Name           Age Monthly_salary
0          Amit            23          90000
1  not eligible  not eligible   not eligible
2  not eligible  not eligible   not eligible
3         Rahul            26          55000
4          samu            24          50000
5          jamu            23          30000

In [45]:
df

    Name  Age  Monthly_salary
0   Amit   23           90000
1  Sumit   22           30000
2   Jadu   22           45000
3  Rahul   26           55000
4   samu   24           50000
5   jamu   23           30000

In [48]:
# add new columns
df['Team'] = ['CEO','HR','CTO','DA','IT','ELE']
df

    Name  Age  Monthly_salary Team
0   Amit   23           90000  CEO
1  Sumit   22           30000   HR
2   Jadu   22           45000  CTO
3  Rahul   26           55000   DA
4   samu   24           50000   IT
5   jamu   23           30000  ELE

In [49]:
df.to_csv('Test_data_WithoutIndex.csv', index = False)

In [50]:
df

    Name  Age  Monthly_salary Team
0   Amit   23           90000  CEO
1  Sumit   22           30000   HR
2   Jadu   22           45000  CTO
3  Rahul   26           55000   DA
4   samu   24           50000   IT
5   jamu   23           30000  ELE

In [51]:
# monthly bonus add 20 percentage

df['Bonus'] = df['Monthly_salary'] * 0.2
df

    Name  Age  Monthly_salary Team    Bonus
0   Amit   23           90000  CEO  18000.0
1  Sumit   22           30000   HR   6000.0
2   Jadu   22           45000  CTO   9000.0
3  Rahul   26           55000   DA  11000.0
4   samu   24           50000   IT  10000.0
5   jamu   23           30000  ELE   6000.0

In [52]:
df.head()

    Name  Age  Monthly_salary Team    Bonus
0   Amit   23           90000  CEO  18000.0
1  Sumit   22           30000   HR   6000.0
2   Jadu   22           45000  CTO   9000.0
3  Rahul   26           55000   DA  11000.0
4   samu   24           50000   IT  10000.0

In [53]:
# add new row 

df.loc[len(df)] = ['kaka',27,60000,'IT',12000]
df

    Name  Age  Monthly_salary Team    Bonus
0   Amit   23           90000  CEO  18000.0
1  Sumit   22           30000   HR   6000.0
2   Jadu   22           45000  CTO   9000.0
3  Rahul   26           55000   DA  11000.0
4   samu   24           50000   IT  10000.0
5   jamu   23           30000  ELE   6000.0
6   kaka   27           60000   IT  12000.0

In [54]:
len(df)

7

In [55]:
# update value index name used 

df.loc[0,'Monthly_salary'] = 95000
df

    Name  Age  Monthly_salary Team    Bonus
0   Amit   23           95000  CEO  18000.0
1  Sumit   22           30000   HR   6000.0
2   Jadu   22           45000  CTO   9000.0
3  Rahul   26           55000   DA  11000.0
4   samu   24           50000   IT  10000.0
5   jamu   23           30000  ELE   6000.0
6   kaka   27           60000   IT  12000.0

In [56]:
# update name columns

df.loc[df.Name == 'Amit','Monthly_salary'] = 97000
df

    Name  Age  Monthly_salary Team    Bonus
0   Amit   23           97000  CEO  18000.0
1  Sumit   22           30000   HR   6000.0
2   Jadu   22           45000  CTO   9000.0
3  Rahul   26           55000   DA  11000.0
4   samu   24           50000   IT  10000.0
5   jamu   23           30000  ELE   6000.0
6   kaka   27           60000   IT  12000.0

In [57]:
# delete value row

df.drop(df[df.Name == 'kaka'].index)

    Name  Age  Monthly_salary Team    Bonus
0   Amit   23           97000  CEO  18000.0
1  Sumit   22           30000   HR   6000.0
2   Jadu   22           45000  CTO   9000.0
3  Rahul   26           55000   DA  11000.0
4   samu   24           50000   IT  10000.0
5   jamu   23           30000  ELE   6000.0

In [58]:
# delete value columns

df.drop('Bonus',axis=1)

    Name  Age  Monthly_salary Team
0   Amit   23           97000  CEO
1  Sumit   22           30000   HR
2   Jadu   22           45000  CTO
3  Rahul   26           55000   DA
4   samu   24           50000   IT
5   jamu   23           30000  ELE
6   kaka   27           60000   IT

In [59]:
df.drop('Bonus',axis=1,inplace = True)

In [61]:
df.rename(columns= {'Monthly_salary' : 'salary'}, inplace = True)

In [62]:
df.to_csv('Test_data_WithoutIndex.csv', index = False)

In [63]:
df

    Name  Age  salary Team
0   Amit   23   97000  CEO
1  Sumit   22   30000   HR
2   Jadu   22   45000  CTO
3  Rahul   26   55000   DA
4   samu   24   50000   IT
5   jamu   23   30000  ELE
6   kaka   27   60000   IT

In [64]:
# value sort

df.sort_values('salary')

    Name  Age  salary Team
1  Sumit   22   30000   HR
5   jamu   23   30000  ELE
2   Jadu   22   45000  CTO
4   samu   24   50000   IT
3  Rahul   26   55000   DA
6   kaka   27   60000   IT
0   Amit   23   97000  CEO

In [65]:
df.sort_values('salary' , ascending = False)

    Name  Age  salary Team
0   Amit   23   97000  CEO
6   kaka   27   60000   IT
3  Rahul   26   55000   DA
4   samu   24   50000   IT
2   Jadu   22   45000  CTO
1  Sumit   22   30000   HR
5   jamu   23   30000  ELE

In [69]:
# working with date value

df['DOJ'] = ['2024-01-01','2024-01-15','2025-03-24','2026-05-27','2026-02-16','2025-04-24','2021-03-24']

In [70]:
df

    Name  Age  salary Team         DOJ
0   Amit   23   97000  CEO  2024-01-01
1  Sumit   22   30000   HR  2024-01-15
2   Jadu   22   45000  CTO  2025-03-24
3  Rahul   26   55000   DA  2026-05-27
4   samu   24   50000   IT  2026-02-16
5   jamu   23   30000  ELE  2025-04-24
6   kaka   27   60000   IT  2021-03-24

In [71]:
df['DOJ'].dtype

dtype('O')

In [72]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [73]:
# convert date and time standerd formate
df['DOJ'].dtype

dtype('<M8[ns]')

In [74]:
df

    Name  Age  salary Team        DOJ
0   Amit   23   97000  CEO 2024-01-01
1  Sumit   22   30000   HR 2024-01-15
2   Jadu   22   45000  CTO 2025-03-24
3  Rahul   26   55000   DA 2026-05-27
4   samu   24   50000   IT 2026-02-16
5   jamu   23   30000  ELE 2025-04-24
6   kaka   27   60000   IT 2021-03-24

In [75]:
# new date created 
# DOJ2
df['DOJ2'] = ['17-01-2019','24-01-2018','25-03-2016','20-05-2000','23-05-2000','19-05-2000','9-05-2000']
df

    Name  Age  salary Team        DOJ        DOJ2
0   Amit   23   97000  CEO 2024-01-01  17-01-2019
1  Sumit   22   30000   HR 2024-01-15  24-01-2018
2   Jadu   22   45000  CTO 2025-03-24  25-03-2016
3  Rahul   26   55000   DA 2026-05-27  20-05-2000
4   samu   24   50000   IT 2026-02-16  23-05-2000
5   jamu   23   30000  ELE 2025-04-24  19-05-2000
6   kaka   27   60000   IT 2021-03-24   9-05-2000

In [77]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [76]:
# this is proper formate
df['DOJ2'] = pd.to_datetime(df['DOJ2'] , format = '%d-%m-%Y')
df

    Name  Age  salary Team        DOJ       DOJ2
0   Amit   23   97000  CEO 2024-01-01 2019-01-17
1  Sumit   22   30000   HR 2024-01-15 2018-01-24
2   Jadu   22   45000  CTO 2025-03-24 2016-03-25
3  Rahul   26   55000   DA 2026-05-27 2000-05-20
4   samu   24   50000   IT 2026-02-16 2000-05-23
5   jamu   23   30000  ELE 2025-04-24 2000-05-19
6   kaka   27   60000   IT 2021-03-24 2000-05-09